provider "aws" {
  region = "us-east-1"
  access_key     = "
  secret_key     = ""
}

resource "aws_instance" "myVM" {
  ami = "the ami ID which was generated by running the packer application script"
  instance_type  = "t2.micro"
  tags = {
    Name = "APP"
  }
}